Repository MycroftAI/documentation, pull requests merged in 2018-08, with the labels that each got.

#81 Update mark-1.md
  _pages/mark-1.md
Labels: CLA: Yes, enhancement

#79 Use correct file name for do.you.like.intent
  _pages/padatious.md
Labels: CLA: Yes, bug

#83 Updated python sample code to python 3
  _pages/automatic-testing.md
  _pages/message-bus.md
  _pages/skill-settings.md
Labels: CLA: Yes
