Repository MycroftAI/documentation, pull requests merged in 2018-06, with the labels that each got.

#66 Update picroft-audio.md
  _pages/picroft-audio.md
Labels: CLA: Needed, bug

#69 Added documentation for mycroft-core PR feature/nice_date
  _pages/configuring-nice-functions.md
Labels: CLA: Yes, enhancement

#73 Add Documentation for Plasma-Mycroft
  _pages/linux.md
  _pages/plasma-mycroft-installation.md
  _pages/plasma-mycroft.md
Labels: CLA: Yes, enhancement

#72 Fix command to change audio source
  _pages/audio-troubleshooting.md
Labels: CLA: Yes, bug
